---
output:
  pdf_document:
    keep_tex: false
    fig_caption: yes
    latex_engine: pdflatex
    template: ./svm-latex-syllabus.tex
geometry: margin=0.85in

title: "Research in Social Media"
author:
    - Lachlan Deer
semester: "Block 4 (Spring) 2021"

email: "lachlan.deer@gmail.com"
web: "YYYYYYY"
classroom: "To Be Announced"
classhours:
- "TBA"
dates: "TBA"
days: "TBA"

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.25}
---


# Motivation

<!---  TODO: more analytics focus ---->

"Some 73% of online adults now use a social networking site of some kind... [and] 42% of online adults now use multiple social networking sites," according to a recent Pew Research survey.^[
Pew Research, 2019, [Social Media Fact Sheet.](https://www.pewresearch.org/internet/fact-sheet/social-media/)
]
If a business needs to be where its customers are, then establishing a strong presence on social media is a critical component of a modern marketing strategy.
The goal of this course is to develop an understanding of the social media landscape from the point of view of a marketing analyst.
To that end, we need to be able to answer the following questions:
How does one develop an online reputation or develop their brand online? 
How does one maintain a strong user community on social networking sites? 
How can one craft a potent social advertising strategy? 
What are the potential pitfalls?
How does one quantitatively assess whether their online reputation is positive and/or improving, or whether their social marketing is effective?

To answer these questions, we must synthesize knowledge from a variety of disciplines. 
Sociologists have researched such concepts as homophily and social capital, which point to the underlying motivations in the relationships of individuals in a social network, 
  computer scientists have uncovered surprising patterns in real-world social networks, 
  and marketing experts have studied how network structure influences consumer demand, what makes ads go 'viral' and aspects of social advertising. 
This course will combine this foundational material with actual case studies of businesses in the social world to build an understanding of modern social media marketing.
As we progress through the course a heavy emphasis on analytical techniques - both statistical and theoretical - will guide our understanding and allow us to draw conclusions from data to answer the questions posed above.

The course is split into four modules:

1. **Network Patterns:** which seeks to describes and explain several common patterns found in real-world social networks,
2. **Branding and Community:** which explores the best practice methods for maintaining a strong brand online and managing the user community,
3. **Importance and Influence:** which discusses an individual's place in the network, and how memes, early adoption, word of mouth and other 'information cascades' propagate,
4. **Advertising and Marketing:** which focuses on viral marketing and social advertising techniques.

# Target Audience

This course is designed for students in the Master of Marketing Analytics and Master of Marketing Management who have a strong interest in social media marketing and 
  want to improve their quantitative and analytical skills.

In particular, I expect the typical student to have the following characteristics:

* Strong interest in understanding how social media and social networks effect consumer behaviour, brand reputation and the actions of marketers.
* Strong interest in learning and applying statistical analysis and data science techniques to social media data, although with limited existing background (see Pre-reqs below).
* Strong interest in using quantitative results to develop management or marketing insights.
* Interest in learning how to write computer code and acquire "best practice" methods.
* Interest in learning new quantitative modelling techniques.
* Ability to work collaboratively.

#  Course Objectives

This course has five closely intertwined objectives:

1. Develop awareness of the challenges and opportunities social media and social networks present marketers.
2. Learning to use quantitative and statistical analysis to develop strategies for managers and marketers on social media platforms.
3. Understanding which modelling or statistical technique is best suited to a particular problem.
4. Develop the ability to understand the limitations of one's analyisis.
5. Acquire neccesary skills to work collaboratively in teams on analytical marketing problems.

Learning objectives for specific modules will be provided within the Course Notes.

# Pedagogy

The course will involve lectures and discussions, web videos, hands on in-class assignments. 
The course strives to balance the practical aspects of social media analytics with a theoretical understanding of the concepts and frameworks involved. 
Each topic covered has a lecture/discussion portion as well as a practicum/exercise/demo portion (called Labs below). 
We include video clips that are designed to introduce you to technical aspects of statistical analysis and computational modelling so that we can focus on marketing substance in lectures.
There are course projects in the form of group assignments and an individual final project where we will work on the developing our analytical toolkit and framing results around answering marketing questions.

# Prerequisites

To do well in this course it us suggested that you have passed the course Introduction to Marketing Research.
<!--- Pre-requisite classes can be taken concurrently with this class if needed. --->

In addition, students will benefit from having completed other marketing courses (Examples) and other classes at TiSEM that deal with data and computing (i.e. the 'skills classes').
These are, however, not required.

# Computing

This course is an applied course, and as such we aim to use, understand and develop computational routines that help managers and marketers make better decisions.
Large portions of the course will be *'hands-on'* and we wil be using the statistical software `R` to demonstrate and apply methods and concepts in class.

All of the software requirements for this course are open-source and/or free. 
Please aim to have everything installed by the start of our first lecture.

*I will be available for installation troubleshooting during the first week of the course.*
*You can sign up for a slot to get installation help [here](TODO:link-to-be-created.com).*

## R & RStudio

You will be required to install `R` and `RStudio` to complete the Labs and group assignments.
Installation instructions are available from the links below (they differ slightly by operating system):

* [Installing `R`](TODO:link-to-be-created.com).
* [Installing RStudio](TODO:link-to-be-created.com).

After installing R and RStudio I suggest you get acquainted with the interface and basic data analysis commands before the first class.
To facilitate the introduction, there are a series of introductory videos and a quiz to test your understanding available on the [course webpage](TODO:link-to-be-created.com).
Please look over these before the first class.

## Improving Reproduciblity of our Analysis with Git and GitHub

In addition to helping you gain analytics skills using `R`, I want to help you improve the reproducibility of your computational analysis - i.e. I want (i) you to document your code and the changes you make to it, and (ii) your code to be able to run on not only your computer, but mine and anyone else's.
To help achieve this goal we will use a version control software called `Git` and we will post our codes on a repository called `GitHub`.

* To install Git and create a Github account, follow [these instructions](TODO:link-to-be-created.com).
* Also regsiter for an education discount to get unlimited private repositories [here](https://education.github.com/discount_requests/new).^[
  GitHub recently [announced](https://blog.github.com/changelog/2019-01-08-pricing-changes/) unlimited free private repos for everyone. 
  However, you are limited to three collaborators per private repo, so the education discount still makes sense.
  ]

An introductory tutorial in video format and a quiz to test your understanding are available on the [course website](TODO:link-to-be-created.com).
Please look over the material before the first class.

### GitHub Classroom

I am going to run the entire course through GitHub Classroom. 
You will receive an email invitation to the course repo with instructions in due time, but for now it suffices to saythat this is how we’ll submit assignments and provide feedback, etc.
Canvas will only be used to distribute grades.

# Evaluation

## Class Participation (5 percent)

Attendance and participation in class is required. 
There will be a set of randomly announced in-class recap quizzes that will be graded on a check/check+ basis. 
If you are not in class you will receive no grade for this quiz. 
There will be four/five such quizzes and I will take the best three to determine your score in addition to a subjective evaluation of your participation in class. 
There is absolutely no make up for these quizzes.

## Homework Assignments (40 percent)

There will be 2 group assignments worth equal weight. 
To pass the assignment, each group member needs to have made a substantial contribution to the project. 
The finished reports (& code where appropriate) must be submitted via GitHub no later than midnight the day of the class (i.e. before 23:59 the day before a class).

The topics for the group assignments are:

* Group Assignment 1: Evaluating & Managing Online Reputation.
    * We will use data from Trip Adviser and some supplementary sources.
* Group Assignment 2: Advertising on Facebook & Analysing Facebook Ads.
    * We use publicly available data provided by Facebook to explore advertising effectiveness on their platform.

Further information on group assignments will be distributed closer to their issue.

## Course Project (55 percent)

You  must develop a project on any topic related to social media analytics that *has marketing implications* (broadly defined) that interests you. 
The final submission of the report has three features: 
  (1) a written report of a max. 10 pages, 
  (2) the underlying code & data to produce the report, and 
  (3) a 5 minute video presentation of your research.

The project should have the following characteristics:

* There should be a clear motivation. You should be trying to solve a question that matters, either to society or business.
* You should do a thorough survey of the relevant literature. This includes articles from the popular press as well as from scholarly sources such as academic journals.
* Your report and video presentation should organize this literature survey appropriately, and summarize your main insights and findings.

To assist you design your project with these characteristics, I have broken the project into three components: (1) proposal, (2) literature review, and (3) a report and video. 
Each component has different due dates *and* contributes to your final grade.

The final grade for your project is computed as:

$$\textrm{Project Grade} = 0.25 \times \textrm{Proposal} 
                         + 0.15 \times \textrm{Literature Review}
                         + 0.60 \times \left( \textrm{Report + Video} \right)
                        $$

## Group Formation

This course has two assignments which **must** be done in groups. 
Students will be **randomly assigned** to groups before the each assignment is released, i.e. the groups will change between assignments. 
Each group will consist of 5 students.

Working with other student's you are unfamiliar with is an important skill to acquire, and mimics aspects of team work in the *real world*.

<!---
## Regrade Policy

If you believe an error has been made in grading your assignments, you may request a re-grade. 
The request must be in writing, must explain the exact concern, and must occur within 7 calendar days of when the graded materials were returned or when the final course grade is posted. 
I reserve the right to re-grade the entire contents of any submitted assignment. 
This means that your grade may go up or down, depending on what is found during the re-grade.
--->

## Late Submission

Assignments and Projects must be submitted before the deadline.
If you submit one assignment late, you will be penalized by 25 percent per calendar day.
This penalty applies to an entire group where applicable.
After the first late submission, you will get zero points on all subsequent late submissions

# Office Hours

We are here to help you through the course & want you meet your expectations and personal learning goals.
To that end, we have scheduled consultation hours each week for you to meet us and discuss aspects of the lecture material, lab sessions and assignments that you are struggling with.
Our office hours are:

\begin{table}[h!]
\begin{center}
\begin{tabular}{lccc}
Name:               & Lachlan Deer &  & FirstName Last Name \\
Office Location:    & XX.XXX       &  & XX.XXX              \\
Consultation Hours: & YY.YYY       &  & YY.YYY              \\
Link to Book Slot:  & ZZ.ZZZ       &  & ZZ.ZZZ             
\end{tabular}
\end{center}
\end{table}

If you plan on coming to our scheduled hours, please make a booking using the links provided.
If you cannot make the scheduled office hours, send us an email with at least three proposed times to meet and we will make it work.
Office Hours are subject to a "fair and equitable use" policy.

I expect you to come to your schedule slot prepared and having clear questions in mind that you want to ask. 
If either of us feel you have come unprepared, we reserve the right to end the appointment and ask you to come back at a future time when you are more prepared.

# Rules of the Game

I have clear expectations of how we should all interact in class and in meetings.
They are summarised by the "7 Be's" below:

## Be Active

Learning via listening to monologues is an ineffective learning technique.
Come to class prepared to ask questions, and to answer questions posed by me and others in class.
Doing so, will lead to a much more pleasant learning experience for us all.
I would much rather have an engaging discussion on topics where we share mutual interest and cover less material than listen to myself talk for 90 minutes at a time.

## Be "Hands-on"
The class is designed to be `hands-on' in the sense that you will be programming a lot of things *during the class*.
We strongly believe the only way to learn programming is to do programming.
Please bring your laptop with you to each session and install the required software before the course begins.
Try to complete each activity we do in class and be prepared to ask and answer questions during class.
Slides or notes will be made available at the beginning of each class, codes that solve exercises will be posted during or after the session.

## Be Prepared

We expect you to dedicate an average of 20 hours per week of study time to this course.
Use this time to look over required readings, re-examine course notes and codes and work on your assignments.
Looking over required readings before class means that our discussions will have more substance, and (ideally) be more insightful.

Quick tip: If you find yourself not understanding part of the course content or not able to find bugs in your code, take a break and come back to it in an hour or so. 
Come talk to us if it remains unclear.

## Be Professional

I expect you to treat us and your class members collegially.
In addition, we have a [Code of Conduct](TODO:add-link.com) that provides further details of acceptable and unacceptable behaviour.
It boils down to "be nice to each other." 

When writing emails, being professional means using a meaningful subject line, identifying yourself (i.e. Regards, Lachlan at the end of the email), and keeping the message focussed.
We aim to reply to emails within 48 hours Monday - Friday, but there might be a slight delay if you write to us late Friday evening. 

I strongly encourage you to provide feedback about both format and content during the course.
Consider your tone when doing so, i.e. don't flame us.

## Be Informal (but not too informal!)

Do not address us with "Mr.", "Dr.", or "Prof.". Please use our first name's (i.e. Lachlan and XXX). 
More formality than that makes me feel uncomfortable.

Also you can to add us on LinkedIn or Twitter - where we maintain professional accounts, but not Facebook.

## Be International

This course is taught in English.
You are obliged to speak English whenever there are international students present. 
If in doubt, you need to speak English.
As someone who has studied in in countries where I do not speak the native language - be assured it is *very much appreciated.*

## Be Healthy (Physically & Mentally)

Physical and Mental health are important, and definitely more important than your coursework.
*If you are feeling ill on the day of a class, I emplore you to stay at home*. 
Material posted online, the readings and talking with your classmates about what you missed is more than enough if you need to miss one or two classes.

On the mental health side, we know how challenging graduate study can be, especially when paired with ones 'non-study life.'
*I strongly encourage you to prioritise mental health over **everything** else.*
I'm happy to talk with you individually and share some common experiences and strategies, but I am not a professional. 
If you feel like you need to talk to someone, a good starting point might be [Tilburg's Education Coordinators](https://www.tilburguniversity.edu/students/tutoring/education-coordinators/economics-management) or the [student psychologists](https://www.tilburguniversity.edu/students/tutoring/psychologist) at the University.


## Be Fair & Honourable 

In group assignments we expect all group members to actively and evenly contribute.
If you are struggling with parts of a group assignment you are working on, talk to your group members and to us rather than withdrawing from conversations with your colleagues. 

Being fair & honourable also means that you should not plagiarise others work.
We stick closely with the School's Fraud and plagiarism policies which are outlined [here](https://www.tilburguniversity.edu/students/studying/regulations/fraud/economics).


\begin{landscape}

\section{Preliminary Schedule}

The following is a preliminary schedule.
It may be updated prior to the beginning of the course, and updated schedule will be forwarded before the course begins.

\begin{table}[h!]
\centering
\begin{tabular}{lllll}
\hline
\multicolumn{1}{l}{Week} & \multicolumn{1}{l}{Lecture Topic}    & \multicolumn{1}{l}{Web Videos} & \multicolumn{1}{l}{Lab Session} & \multicolumn{1}{l}{Assignments} \\ \hline
\multirow{2}{*}{0}         & \multirow{2}{*}{(Before First Class)} & Course Introduction             & R Introduction*                  & \multirow{2}{*}{Working with R*} \\
                           &                                       & Introduction to R               & Exploratory Data Analysis*       &                                  \\
                           &                                       & Introduction to Git             &                                  & Git Basics*                      \\
                           \hline
                           & \multicolumn{4}{l}{\textbf{Topic 1: Network Patterns}}                                                                                        \\
                           \hline
1                          & Social Network Patterns               &                                 & Describing \& Visualizing        &                                  \\
                           &                                       &                                 & Network Data                     &                                  \\
                           \hline
                           & \multicolumn{4}{l}{\textbf{Topic 2: Branding \& Community}}                                                                                   \\
                           \hline
2                          & Online Reputation                     &                                 &  Regression: OLS \& Diff in Diff &  Group Assignment 1 released     \\
3                          & Community Structure                   &                                 & Text Analytics: Basics          &  Project Proposals Due           \\
                           \hline
                           & \multicolumn{4}{l}{\textbf{Topic 3: Importance \& Influence}}                                                                                 \\
                           \hline
4                          & Epidemics, Gossip \& Word of Mouth    &                                 & Endogeneity: Instrumental Variables           &  Group Assignment 1 Due          \\
5                          & Influencers                           &                                 & Simulating Network Evolution     &  Group Assignment 2 released     \\
                           &                                       &                                 &                                  &  Project Lit. Review Due         \\
                            \hline
                           & \multicolumn{4}{l}{\textbf{Topic 4: Advertising \& Marketing}}                                                                                \\
                           \hline
6                          & Internet Marketing \& Viral Marketing &                                 &                                  &                                  \\
7                          & Social Advertising                    &                                 &                                  &                                  \\
8                          & {[}Final Exam?{]}                     &                                 &                                  &  Group Assignment 2 Due          \\
                           &                                       &                                 &                                  &  Project Due                     \\
\end{tabular}
\end{table}

\end{landscape}
\restoregeometry

\newpage

# Readings

## Textbooks

We will combine material from two books, recent papers and case studies.
All readings from books are optional.

## Books

The course uses readings from the following books:

* *Networks, Crowds and Markets: Reasoning About a Highly Connected World*, by David Easley and Jon Kleinberg
* *Networks: An Introduction* by Mark Newman

## Case Studies

<!--- TODO: Access to cases for students and instructors --->

Case studies will be provided as an online course pack [here]().

* Managing Online Reviews on Trip Adviser 
* TopCoder: Developing Software through Crowdsourcing
* HubSpot: Inbound Marketing and Web 2.0

## Papers

<!--- TO DO: Link using Tilburg's Library links --->

**Week 1: Network Patterns**


[Origins of Homophily in an Evolving Social Network](https://research.google.com/pubs/archive/35626.pdf)

[Birds of a Feather: Homophily in Social Networks](https://www.researchgate.net/profile/Lynn_Smith-Lovin/publication/200110353_Birds_of_a_Feather_Homophily_in_Social_Networks/links/55e1b60b08ae6abe6e8c228c/Birds-of-a-Feather-Homophily-in-Social-Networks.pdf)

**Week 2: Online Reputation**

[What is online reputation marketing? Is it important?](https://thriveagency.com/news/what-is-online-reputation-marketing/)

[5 examples of online reputation management done right](https://www.smartinsights.com/digital-marketing-strategy/online-reputation-management-done-right/)

[When and how Managers' Responses to Online Reviews Affect Subsequent Reviews](https://journals.sagepub.com/doi/10.1509/jmr.15.0511)

[Fake It Till You Make It: Reputation, Competition, and Yelp Review Fraud](http://people.bu.edu/zg/publications/fakereviews.pdf)

**Week 3: Community Structure**

[Mapping Twitter Topic Networks: From Polarized Crowds to Community Clusters](https://www.pewresearch.org/internet/2014/02/20/mapping-twitter-topic-networks-from-polarized-crowds-to-community-clusters/)

[Detecting, Preventing, and Mitigating Online Firestorms in Brand Communities](https://journals.sagepub.com/doi/10.1177/0022242918822300)

[Brand community integration, participation and commitment: A comparison between consumer-run and company-managed communities](https://www.sciencedirect.com/science/article/abs/pii/S0148296319306630?via%3Dihub)

[Managing the product-harm crisis in the digital era: The role of consumer online brand community engagement](https://www.sciencedirect.com/science/article/abs/pii/S014829632030268X?via%3Dihub)

**Week 4: Epidemics, Gossip & Word of Mouth**

[Rumor Cascades](http://www.aaai.org/ocs/index.php/ICWSM/ICWSM14/paper/view/8122/8110)

[Social Influence & the diffusion of user-generated content](http://dl.acm.org.ezproxy.lib.utexas.edu/citation.cfm?id=1566421)

[Does online word of mouth increase demand?(and how?) evidence from a natural experiment](https://pubsonline.informs.org/doi/pdf/10.1287/mksc.2017.1045?casa_token=7zN_o-j7KUMAAAAA:rVU0bXlN4kN76-m6969YvLrXtIQUnQoRAVWxyUAQKYwsEL8ZF2cTpiPjmXxdVuR-cI7rK5z4lRE)

[The Effects of Online User Reviews on Movie Box Office Performance: Accounting for Sequential Rollout and Aggregation Across Local Markets](https://pubsonline.informs.org/doi/abs/10.1287/mksc.1100.0572)

[Online Word of Mouth and the Performance of New Products](http://lachlandeer.github.io/files/deer_jmp.pdf)

[Does Twitter matter? The impact of microblogging word of mouth on consumers’ adoption of new movies](https://openaccess.city.ac.uk/id/eprint/12656/1/)

**Week 5: Influencers**

[Influencing the Influencers](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3376904)

[Advertising to early trend propagators: Evidence from twitter](https://dspace.mit.edu/bitstream/handle/1721.1/122363/SSRN-id2419743.pdf?sequence=2&isAllowed=y)

[A Framework for Analyzing Influencer Marketing in Social Networks: Selection and Scheduling of Influencers](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3255198)

[Seeking Micro-influencers for Brand Promotion](https://dl.acm.org/doi/pdf/10.1145/3343031.3351080?casa_token=sblzM8Rq8UMAAAAA:K_RBk8Cit7uNMvPt-8dK_pOK2c8JgyjBSZmpBqRTaAVQUup88fhTDf48dcOJHWajEF80vrxuxVsF)

[Social Influence Maximization under Empirical Influence Models](https://www.nature.com/articles/s41562-018-0346-z)

**Week 6: Internet Marketing & Viral Marketing**

[Creating Contagion Through Viral Product Design](http://misrc.umn.edu/workshops/2011/spring/AralVPDFinal1110.pdf)

[The Dynamics of Viral Marketing](http://arxiv.org/pdf/physics/0509039.pdf)

[Propagators, Creativity, and Informativeness: What Helps Ads Go Viral](https://www.sciencedirect.com/science/article/abs/pii/S1094996819300507)

[What Drives Virality (Sharing) of Online Digital Content? The Critical Role of Information, Emotion, and Brand Prominence](https://journals.sagepub.com/doi/10.1177/0022242919841034)

[Selection Effects of Online Sharing: Consequences for Peer Adoption](http://arxiv.org/pdf/1311.2878.pdf)

**Week 7: Social Advertising**

[Social Media Buyers Guide](https://www.iab.com/insights/social-media-buyers-guide/)

[Social Influence in Social Advertising: Evidence from Field Experiments](https://arxiv.org/pdf/1206.4327.pdf)

[Social Advertising Eﬀectiveness Across Products: A Large-Scale Field Experiment](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3610384)

[A Comparison of Approaches to Advertising Measurement: Evidence from Big Field Experiments at Facebook](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3033144)

[Tweeting as a marketing tool: A field experiment in the TV industry](https://dspace.mit.edu/bitstream/handle/1721.1/120756/0c43ccabbc71b279f98115faf27e18330807.pdf?sequence=1&isAllowed=y)

[The Ripple Effect of Firm-Generated Content for New Movie Releases](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3336856)

[Improvised Marketing Interventions in Social Media](https://journals.sagepub.com/doi/10.1177/0022242919899383)

# FAQs

**R looks cool, but I’m more familiar with Python/Julia/MatLab/SPSS/etc. Can I use that instead?**

Short answer: No. 

Longer answer: Look, I like and use a lot of those languages too, but I’m not changing
my lecture notes or assignment templates for you. 
Plus, I really do think that R makes the most sense for quantitative marketing students looking to develop their data science skills. 
It already has all of the statistics and econometrics support, and is amazingly adaptable as a “glue” language to other programming languages and APIs. 
Learning multiple languages is never a bad idea in the long run, though.

**I already have a BitBucket/GitLab/etc. account. Do I still have to use GitHub?**

Since I’m running this course through GitHub Classroom, yes. But good for you! (Seriously... those are great platforms too and as an open-source advocate, I fully support a plurality of tools and software options.)

**On that note, do you have any advice for running a course on GitHub Classroom?**

I mostly followed [this excellent tutorial](https://github.com/jfiksel/github-classroom-for-teachers) by Jacob Fiksel.
(Hat Tip to Grant McDermott at U Oregon for recommending this!)

**This course looks interesting! Can I use/adapt your lecture notes for a similar course that I’m teaching at XYZ?**

Sure. 
I’ve benefited greatly from other people making their teaching materials publicly available (and have tried my best to acknowledge them directly in the relevant sections of this course). 
I’m more than happy to pay it forward.
I only ask two small favours. 
1) Please let me know (email/Twitter) if you do use material from this course, or have found it useful in other ways. 
2) A minor acknowledgment somewhere in your own syllabus or notes would be much appreciated.